on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/release-please-action@v1
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: release-please-action
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: JasonEtco/build-and-tag-action@v1
        with:
          setup: ''
          tag_name: ${{ steps.release.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.release.outputs.tag_name
